name: Docker Image CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:latest
    - name: Docker publish
      run: docker push ${{secrets.DOCKER_USER}}/${{ github.event.repository.name }}
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASS }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
